version: "3.8"

services:
  mysql:
    image: mysql:8.3.0
    container_name: mysql
    hostname: mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=Asia/Seoul
    ports:
      - 3306:3306
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql # 'Create databses' sql script as using mutliple databases


  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dev-exchange
    hostname: dev-exchange
    ports:
      - 8000:8000
    env_file:
      - .env
    links:
      - mysql
    depends_on:
      - mysql