// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_W8lzLjixiYsqT0aLN6h6gXd6G04Ydz4',
    appId: '1:746747507982:web:4a37cd3be9255b7804935f',
    messagingSenderId: '746747507982',
    projectId: 'capstone2024-783c5',
    authDomain: 'capstone2024-783c5.firebaseapp.com',
    storageBucket: 'capstone2024-783c5.appspot.com',
    measurementId: 'G-ZLBZVEN3L7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwLEo2mTVfw2Z7Sk_rqaGxXswwk_KmhA0',
    appId: '1:746747507982:android:cc2aac9cea495ed504935f',
    messagingSenderId: '746747507982',
    projectId: 'capstone2024-783c5',
    storageBucket: 'capstone2024-783c5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEq8J6gm57EUzyncfKr5MEGFc7I4aOCAE',
    appId: '1:746747507982:ios:7f803f4277ae79ac04935f',
    messagingSenderId: '746747507982',
    projectId: 'capstone2024-783c5',
    storageBucket: 'capstone2024-783c5.appspot.com',
    iosBundleId: 'com.example.suntown',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEq8J6gm57EUzyncfKr5MEGFc7I4aOCAE',
    appId: '1:746747507982:ios:7f803f4277ae79ac04935f',
    messagingSenderId: '746747507982',
    projectId: 'capstone2024-783c5',
    storageBucket: 'capstone2024-783c5.appspot.com',
    iosBundleId: 'com.example.suntown',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_W8lzLjixiYsqT0aLN6h6gXd6G04Ydz4',
    appId: '1:746747507982:web:bec730ff2134687b04935f',
    messagingSenderId: '746747507982',
    projectId: 'capstone2024-783c5',
    authDomain: 'capstone2024-783c5.firebaseapp.com',
    storageBucket: 'capstone2024-783c5.appspot.com',
    measurementId: 'G-GDPFYZB3P3',
  );
}
