spring:
  datasource:
      url: jdbc:mysql://localhost:3306/admin?serverTimezone=Asia/Seoul
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: ${DATASOURCE_ADMIN_PASSWORD}

server:
  port: 8070