# 환경변수
app:
  qr:
    key: ${QR_KEY}
    algorithm: ${QR_ALGORITHM}

haetsal-url: ${HAETSAL_URL}

server:
  port: 8080

spring:
  application:
    name: EUM-BANK
  datasource:
    url: jdbc:mysql://${BANK_DB_IP}:${BANK_DB_PORT}/${BANK_DB_NAME}?useUnicode=true&serverTimezone=Asia/Seoul
    username: ${BANK_DB_USERNAME}
    password: ${BANK_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    time-zone: Asia/Seoul
  jpa:
    show-sql: true
    database: mysql
    ddl-auto: update
    generate-ddl: false
    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true
    hibernate:
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL}
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}