name: deploy

on:
  push:
    branches: [ "55-back-타임페이와-연동" ]


jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: "temurin"

      - name: Make application.yml
        run: |
          cd ./src/main/resources
          touch ./application.yml
          echo "${{ secrets.BANK_YML }}" > ./application.yml
        shell: bash

      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew clean build -x test

      - name: Docker build & push to docker hub
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME_YSY }} -p ${{ secrets.DOCKER_PASSWORD_YSY }}
          docker build -t ${{ secrets.DOCKER_REPO_BANK }} .
          docker push ${{ secrets.DOCKER_REPO_BANK }}

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_BANK }}
          username: ${{ secrets.HOSTNAME_BANK }}
          key: ${{ secrets.KEY_BANK }}
        script: |
          docker pull ${{ secrets.DOCKER_REPO_BANK }}
          cd EUM-Bank-docker
          docker-compose up --build
          docker image prune -f